---
- hosts: all
  become: true
  tasks:

  - name: Update Repo
    yum:
      update_cache: yes
  
  - name: install apache2 package
    yum: 
      name: httpd
      state: latest

  - name: Add php support
    yum: 
      name: php
      state: latest
