---
- hosts: all
  become: true
  tasks:

  - name: Update Repo
    yum:
      update_cache: yes
  
  - name: install apache2 package
    yum: 
      name: httpd
      state: latest

  - name: Add php support
    yum: 
      name: php
      state: latest
   
  - name: Update Repo
    apt:
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add php support
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
