---
- hosts: all
  become: true
  tasks:

  - name: Install updates in centOS
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
 
  - name: Install updates in ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: webservers
  become: true
  tasks:
  
  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: install apache and php for CentOS servers
    tags: apache,httpd,centos
    dnf:
     name:
        - httpd
        - php
     state: latest
   
  - name: install mariadb server
    tags: mariadb,db,ubunut
    apt:
     name: mariadb-server
     state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: install samba package
    tags: samba
    package:
     name: samba
     state: latest
