---
- hosts: all
  become: true
  tasks:

  - name: Install updates in centOS
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
 
  - name: Install updates in ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: webservers
  become: true
  tasks:
  
  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: install apache and php for CentOS servers
    tags: apache,httpd,centos
    dnf:
     name:
        - httpd
        - php
     state: latest
   
  - name: install mariadb server
    tags: mariadb,db,ubunut
    apt:
     name: mariadb-server
     state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: install samba package
    tags: samba
    package:
     name: samba
     state: latest

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin sam@gmail.com 
    register: httpd

  - name: restart httpd in centos
    tags: apache,httpd,centos
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

  - name: Copy default HTML file to server
    tags: apache,apache2,httpd
    copy:
     src: ./files/default_site.yml
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

  - name: start httpd (Centos)
    tags: httpd,service,apache,centos
    service:
       name: httpd
       state: started
       enabled: yes
