 - name: install mariadb server package (CentOS)
   tags: centos,db,mariadb
   dnf:
     name: httpd
     state: latest
 
 - name: install mariadb server
   tags: db,mariadb,ubuntu
   apt:
     name: mariadb-server
     state: latest
   when: ansible_distribution == "Ubuntu"
